name: iOS-ipa-build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🍎 Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: 🔨 Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: 📁 Create Payload folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: 📦 Move app to Payload
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: 🗜️ Create IPA file
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: 🚀 Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: ${{ github.ref_name }}
          overwrite: true
          body: "iOS IPA build from GitHub Actions"
